"""Initial migration 4

Revision ID: 66c710f4deb9
Revises: 6cbd34fdd782
Create Date: 2025-07-30 17:34:26.141108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c710f4deb9'
down_revision: Union[str, Sequence[str], None] = '6cbd34fdd782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
