"""Initial migration 5

Revision ID: b09a489dcbb2
Revises: 66c710f4deb9
Create Date: 2025-07-30 17:37:10.536716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09a489dcbb2'
down_revision: Union[str, Sequence[str], None] = '66c710f4deb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'is_active')
    # ### end Alembic commands ###
