"""Update Receipt table with new fields

Revision ID: b4e0567df33a
Revises: b09a489dcbb2
Create Date: 2025-07-31 00:37:22.950246

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e0567df33a'
down_revision: Union[str, Sequence[str], None] = 'b09a489dcbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('store_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('receipt', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('receipt', sa.Column('store_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('receipt', sa.Column('cashier_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('receipt', sa.Column('barcode_num', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('receipt', sa.Column('items', sa.JSON(), nullable=True))
    op.add_column('receipt', sa.Column('payment_details', sa.JSON(), nullable=True))
    op.add_column('receipt', sa.Column('additional_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'additional_info')
    op.drop_column('receipt', 'payment_details')
    op.drop_column('receipt', 'items')
    op.drop_column('receipt', 'barcode_num')
    op.drop_column('receipt', 'cashier_number')
    op.drop_column('receipt', 'store_number')
    op.drop_column('receipt', 'phone_number')
    op.drop_column('receipt', 'store_address')
    # ### end Alembic commands ###
